<?php

namespace Database\Seeders;

use App\Models\DiagnosisCode;
use Illuminate\Database\Seeder;

class DiagnosisCodeSeeder extends Seeder
{
    /**
     * Master kode diagnosis gigi: ICD-10 (blok K00-K14), ICD-9-CM (grup 23-24),
     * dan subset SNOMED CT gigi — lengkap dengan sinonim bahasa awam untuk
     * autocomplete. Produksi: impor penuh dari terminologi Kemenkes.
     */
    public function run(): void
    {
        $rows = [
            // ── ICD-10: penyakit gigi & mulut (K00-K14) ──────────────────────
            ['system' => 'ICD10', 'code' => 'K00.0', 'category' => 'ortodonsia',
                'display_id' => 'Gigi anodon/hypodontia (gigi tidak tumbuh)',
                'display_en' => 'Anodontia', 'keywords' => ['gigi tidak tumbuh', 'anodontia', 'hypodontia']],
            ['system' => 'ICD10', 'code' => 'K00.6', 'category' => 'ortodonsia',
                'display_id' => 'Gangguan erupsi gigi (gigisembunyi/impaksi)',
                'display_en' => 'Disturbances in tooth eruption', 'keywords' => ['gigi bengkak erupsi', 'impaksi', 'gigi sembunyi']],
            ['system' => 'ICD10', 'code' => 'K01.1', 'category' => 'bedah-mulut',
                'display_id' => 'Gigi impaksi (gigi tumbuh terbenam)',
                'display_en' => 'Impacted teeth', 'keywords' => ['gigi bungsu impaksi', 'gigi terbenam', 'impaksi']],
            ['system' => 'ICD10', 'code' => 'K02.0', 'category' => 'konservasi',
                'display_id' => 'Karies email (gigi berlubang lapisan email)',
                'display_en' => 'Dental caries limited to the enamel', 'keywords' => ['gigi berlubang', 'karies', 'lubang kecil']],
            ['system' => 'ICD10', 'code' => 'K02.1', 'category' => 'konservasi',
                'display_id' => 'Karies dentin (gigi berlubang sampai lapisan dentin)',
                'display_en' => 'Dental caries of dentine', 'keywords' => ['gigi berlubang', 'karies', 'lubang gigi', 'ngilu makan manis']],
            ['system' => 'ICD10', 'code' => 'K02.2', 'category' => 'konservasi',
                'display_id' => 'Karies sementum (akar gigi berlubang)',
                'display_en' => 'Dental caries of cementum', 'keywords' => ['akar berlubang', 'karies akar']],
            ['system' => 'ICD10', 'code' => 'K02.9', 'category' => 'konservasi',
                'display_id' => 'Karies gigi tak spesifik',
                'display_en' => 'Dental caries, unspecified', 'keywords' => ['gigi berlubang', 'karies', 'ngilu']],
            ['system' => 'ICD10', 'code' => 'K03.1', 'category' => 'konservasi',
                'display_id' => 'Abrasi gigi (keausan leher gigi)',
                'display_en' => 'Abrasion of teeth', 'keywords' => ['leher gigi cepat', 'abrasi', 'gosok gigi keras']],
            ['system' => 'ICD10', 'code' => 'K03.2', 'category' => 'konservasi',
                'display_id' => 'Erosi gigi (mail gigi tergerus asam)',
                'display_en' => 'Erosion of teeth', 'keywords' => ['gigi tergerus asam', 'erosi', 'mail tipis']],
            ['system' => 'ICD10', 'code' => 'K03.4', 'category' => 'konservasi',
                'display_id' => 'Hiperasemen (semen gigi berlebih)',
                'display_en' => 'Hypercementosis', 'keywords' => ['hiperasemen']],
            ['system' => 'ICD10', 'code' => 'K04.0', 'category' => 'endodonti',
                'display_id' => 'Pulpitis (radang saraf gigi)',
                'display_en' => 'Pulpitis', 'keywords' => ['saraf radang', 'sakit berdenyut', 'nyari malam', 'pulpitis']],
            ['system' => 'ICD10', 'code' => 'K04.1', 'category' => 'endodonti',
                'display_id' => 'Nekrosis pulp (saraf gigi mati)',
                'display_en' => 'Necrosis of the pulp', 'keywords' => ['saraf mati', 'gigi hitam', 'nekrosis']],
            ['system' => 'ICD10', 'code' => 'K04.4', 'category' => 'endodonti',
                'display_id' => 'Granuloma apikal (radang kronis ujung akar)',
                'display_en' => 'Apical periodontitis of pulpal origin', 'keywords' => ['granuloma', 'radang ujung akar', 'ngilu saat digigit']],
            ['system' => 'ICD10', 'code' => 'K04.7', 'category' => 'endodonti',
                'display_id' => 'Abses periapikal (nanah di ujung akar gigi)',
                'display_en' => 'Periapical abscess without sinus', 'keywords' => ['nanah', 'abses', 'bengkak pipi', 'nyeri berdenyut']],
            ['system' => 'ICD10', 'code' => 'K04.99', 'category' => 'endodonti',
                'display_id' => 'Penyakit pulp & periapikal lain (radang jaringan sekitar akar)',
                'display_en' => 'Other diseases of pulp and periapical tissues', 'keywords' => ['radang akar', 'periapikal']],
            ['system' => 'ICD10', 'code' => 'K05.0', 'category' => 'periodonsia',
                'display_id' => 'Gingivitis akut (radang gusi mendadak)',
                'display_en' => 'Acute gingivitis', 'keywords' => ['gusi bengkak mendadak', 'gusi radang', 'gingivitis akut']],
            ['system' => 'ICD10', 'code' => 'K05.1', 'category' => 'periodonsia',
                'display_id' => 'Gingivitis kronis (radang gusi menahun)',
                'display_en' => 'Chronic gingivitis', 'keywords' => ['gusi berdarah', 'radang gusi', 'gusi bengkak', 'bau mulut']],
            ['system' => 'ICD10', 'code' => 'K05.2', 'category' => 'periodonsia',
                'display_id' => 'Periodontitis akut (radang gusi mendalam mendadak)',
                'display_en' => 'Acute periodontitis', 'keywords' => ['gusi nyeri hebat', 'periodontitis akut']],
            ['system' => 'ICD10', 'code' => 'K05.3', 'category' => 'periodonsia',
                'display_id' => 'Periodontitis kronis (gusi menahun, gigi goyang)',
                'display_en' => 'Chronic periodontitis', 'keywords' => ['gigi goyang', 'gusi menurun', 'kantong gusi', 'periodontitis']],
            ['system' => 'ICD10', 'code' => 'K06.0', 'category' => 'periodonsia',
                'display_id' => 'Recesi gingiva (gusi menurun/akar terbuka)',
                'display_en' => 'Gingival recession', 'keywords' => ['gusi turun', 'akar kelihatan', 'recesi']],
            ['system' => 'ICD10', 'code' => 'K06.9', 'category' => 'periodonsia',
                'display_id' => 'Gangguan gusi tak spesifik',
                'display_en' => 'Gingival and periodontal disorder, unspecified', 'keywords' => ['gangguan gusi']],
            ['system' => 'ICD10', 'code' => 'K07.0', 'category' => 'ortodonsia',
                'display_id' => 'Anomali ukuran rahang (rahang kecil/besar)',
                'display_en' => 'Major anomalies of jaw size', 'keywords' => ['rajang kecil', 'rajang besar', 'anomali rahang']],
            ['system' => 'ICD10', 'code' => 'K07.1', 'category' => 'ortodonsia',
                'display_id' => 'Anomali hubungan rahang (maloklusi)',
                'display_en' => 'Anomalies of relationship of the jaws', 'keywords' => ['gigi tak sejajar', 'maloklusi', 'gigitan terbalik']],
            ['system' => 'ICD10', 'code' => 'K07.3', 'category' => 'ortodonsia',
                'display_id' => 'Anomali posisi gigi (berjejal/berderet tak rapi)',
                'display_en' => 'Anomalies of tooth position', 'keywords' => ['gigi berjejal', 'gigi bertumpuk', 'gigi tak rapi', 'malposisi']],
            ['system' => 'ICD10', 'code' => 'K08.8', 'category' => 'prostodonsia',
                'display_id' => 'Gangguan lain gigi & jaringan pendukung',
                'display_en' => 'Other disorders of teeth and supporting structures', 'keywords' => ['gangguan gigi lain']],
            ['system' => 'ICD10', 'code' => 'K09.0', 'category' => 'bedah-mulut',
                'display_id' => 'Kista odontogenik (benjolan berisi cairan gigi)',
                'display_en' => 'Developmental odontogenic cysts', 'keywords' => ['kista gigi', 'benjolan gusi', 'kista odontogenik']],
            ['system' => 'ICD10', 'code' => 'K10.0', 'category' => 'bedah-mulut',
                'display_id' => 'Kelainan tulang rahang (exostosis/tori)',
                'display_en' => 'Developmental disorders of jaws', 'keywords' => ['torus', 'rajang benjolan', 'exostosis']],
            ['system' => 'ICD10', 'code' => 'K11.0', 'category' => 'bedah-mulut',
                'display_id' => 'Hipertrofi kelenjar ludah',
                'display_en' => 'Enlargement of salivary glands', 'keywords' => ['kelenjar ludah bengkak']],
            ['system' => 'ICD10', 'code' => 'K11.4', 'category' => 'bedah-mulut',
                'display_id' => 'Kelenjar ludah tersumbat (sialolitiasis)',
                'display_en' => 'Obstruction in salivary duct', 'keywords' => ['kelenjar ludah tersumbat', 'sialolitiasis']],
            ['system' => 'ICD10', 'code' => 'K12.0', 'category' => 'bedah-mulut',
                'display_id' => 'Afta rekuren (sariawan berulang)',
                'display_en' => 'Recurrent oral aphthae', 'keywords' => ['sariawan', 'afta', 'luka mulut berulang']],
            ['system' => 'ICD10', 'code' => 'K12.2', 'category' => 'bedah-mulut',
                'display_id' => 'Selulitis & abses mulut (bengkak infeksi menyebar)',
                'display_en' => 'Phlegmon and abscess of mouth', 'keywords' => ['bengkak infeksi', 'abses mulut', 'selulitis']],
            ['system' => 'ICD10', 'code' => 'K13.4', 'category' => 'bedah-mulut',
                'display_id' => 'Leukoplakia & gangguan mukosa mulut (bercak putih)',
                'display_en' => 'Leukoplakia and other disturbances of oral epithelium', 'keywords' => ['bercak putih mulut', 'leukoplakia']],
            ['system' => 'ICD10', 'code' => 'K13.79', 'category' => 'bedah-mulut',
                'display_id' => 'Lainnya kelainan bibir & mukosa mulut',
                'display_en' => 'Other lesions of oral mucosa', 'keywords' => ['luka mulut', 'mukosa']],
            ['system' => 'ICD10', 'code' => 'K14.0', 'category' => 'bedah-mulut',
                'display_id' => 'Glossitis (lidah merah radang)',
                'display_en' => 'Glossitis', 'keywords' => ['lidah radang', 'lidah merah', 'glossitis']],
            ['system' => 'ICD10', 'code' => 'K14.8', 'category' => 'bedah-mulut',
                'display_id' => 'Kelainan lidah lain (papil bergerigi dsb.)',
                'display_en' => 'Other diseases of tongue', 'keywords' => ['lidah terasa aneh', 'kelainan lidah']],

            // ── ICD-9-CM: prosedur gigi (grup 23-24) ────────────────────────
            ['system' => 'ICD9', 'code' => '23.1', 'category' => 'konservasi',
                'display_id' => 'Restorasi gigi satu permukaan (tambal 1 permukaan)',
                'display_en' => 'Restoration of tooth by filling - one surface', 'keywords' => ['tambal gigi', 'tambal 1 sisi', 'restorasi']],
            ['system' => 'ICD9', 'code' => '23.2', 'category' => 'konservasi',
                'display_id' => 'Penambalan gigi (restorasi)',
                'display_en' => 'Restoration of tooth by filling', 'keywords' => ['tambal gigi', 'tampal', 'restorasi']],
            ['system' => 'ICD9', 'code' => '23.3', 'category' => 'endodonti',
                'display_id' => 'Pulpotomi (pengangkatan sebagian saraf gigi)',
                'display_en' => 'Pulpotomy', 'keywords' => ['pulpotomi', 'saraf sebagian']],
            ['system' => 'ICD9', 'code' => '23.4', 'category' => 'endodonti',
                'display_id' => 'Pulpektomi (pengangkatan saraf gigi)',
                'display_en' => 'Pulpectomy', 'keywords' => ['pulpektomi', 'ambil saraf gigi']],
            ['system' => 'ICD9', 'code' => '23.7', 'category' => 'endodonti',
                'display_id' => 'Perawatan saluran akar (root canal treatment)',
                'display_en' => 'Root canal therapy', 'keywords' => ['root canal', 'perawatan syaraf gigi', 'obturasi']],
            ['system' => 'ICD9', 'code' => '23.19', 'category' => 'bedah-mulut',
                'display_id' => 'Pencabutan gigi (ekstraksi)',
                'display_en' => 'Other surgical extraction of tooth', 'keywords' => ['cabut gigi', 'ekstraksi', 'cabut']],
            ['system' => 'ICD9', 'code' => '23.41', 'category' => 'bedah-mulut',
                'display_id' => 'Apikoektomi (operasi ujung akar gigi)',
                'display_en' => 'Apicoectomy', 'keywords' => ['apikoektomi', 'operasi akar gigi']],
            ['system' => 'ICD9', 'code' => '23.5', 'category' => 'bedah-mulut',
                'display_id' => 'Pengecoran/penyambungan kekuatan gigi (cast & bahan tambahan)',
                'display_en' => 'Repair of chipped tooth', 'keywords' => ['perbaikan gigi patah', 'gigi retak']],
            ['system' => 'ICD9', 'code' => '24.0', 'category' => 'prostodonsia',
                'display_id' => 'Pemasangan mahkota gigi (crown)',
                'display_en' => 'Insertion of crown', 'keywords' => ['crown', 'mahkota gigi', 'tumpalan sekaligus']],
            ['system' => 'ICD9', 'code' => '24.1', 'category' => 'prostodonsia',
                'display_id' => 'Pemasangan jembatan gigi (bridge)',
                'display_en' => 'Insertion of fixed bridgework', 'keywords' => ['bridge gigi', 'jembatan gigi', 'gigi cekat']],
            ['system' => 'ICD9', 'code' => '23.71', 'category' => 'periodonsia',
                'display_id' => 'Skaling & perawatan gusi (scaling)',
                'display_en' => 'Gingival curettage', 'keywords' => ['scaling', 'bersih karang gigi', 'karang gigi', 'skaling']],
            ['system' => 'ICD9', 'code' => '23.9', 'category' => 'konservasi',
                'display_id' => 'Perawatan gigi lainnya (fluoride dll.)',
                'display_en' => 'Other restorative and preventive dental procedures', 'keywords' => ['fluoride', 'perawatan pencegahan']],
            ['system' => 'ICD9', 'code' => '24.4', 'category' => 'bedah-mulut',
                'display_id' => 'Bedah mulut lainnya (frenulektomi dsb.)',
                'display_en' => 'Other operations on teeth and gums', 'keywords' => ['frenulektomi', 'operasi gusi']],

            // ── SNOMED CT: kondisi klinis gigi (subset) ──────────────────────
            ['system' => 'SNOMED', 'code' => '3723001', 'category' => 'ortodonsia',
                'display_id' => 'Gigi berjejal (crowding)',
                'display_en' => 'Crowded teeth', 'keywords' => ['gigi berjejal', 'gigi bertumpuk', 'gigi tidak rapi']],
            ['system' => 'SNOMED', 'code' => '61818005', 'category' => 'ortodonsia',
                'display_id' => 'Maloklusi (gigitan tak sejajar)',
                'display_en' => 'Malocclusion', 'keywords' => ['maloklusi', 'gigitan salah', 'gigi tak sejajar']],
            ['system' => 'SNOMED', 'code' => '80967001', 'category' => 'periodonsia',
                'display_id' => 'Gusi berdarah (gingival bleeding)',
                'display_en' => 'Bleeding gums', 'keywords' => ['gusi berdarah', 'gusi keluar darah']],
            ['system' => 'SNOMED', 'code' => '109585003', 'category' => 'bedah-mulut',
                'display_id' => 'Impaksi gigi bungsu',
                'display_en' => 'Impacted wisdom tooth', 'keywords' => ['gigi bungsu', 'gigi bungsu impaksi', 'gigi sembunyi']],
            ['system' => 'SNOMED', 'code' => '26231001', 'category' => 'ortodonsia',
                'display_id' => 'Diastema (celah gigi depan)',
                'display_en' => 'Diastema', 'keywords' => ['celah gigi', 'gigi renggang', 'diastema']],
            ['system' => 'SNOMED', 'code' => '309670003', 'category' => 'konservasi',
                'display_id' => 'Gigi sehat (sound tooth)',
                'display_en' => 'Sound tooth', 'keywords' => ['gigi sehat', 'sound']],
        ];

        foreach ($rows as $row) {
            DiagnosisCode::updateOrCreate(
                ['system' => $row['system'], 'code' => $row['code']],
                [...$row, 'source' => 'seed-awal', 'version' => 'v1', 'is_active' => true]
            );
        }
    }
}
